apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: dev-taxi-svc-binding
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'ishitasequeira/taxi'
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: github-webhook-secret-taxi-svc
    name: app-ci-build-from-pr-taxi-svc
    template:
      name: app-ci-template
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'ishitasequeira/bus1'
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: github-webhook-secret-bus1
    name: app-ci-build-from-pr-bus1
    template:
      name: app-ci-template
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'ishitasequeira/gitops2'
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: ci-dryrun-from-pr
    template:
      name: ci-dry-run-from-pr-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/gitops2') && body.ref.startsWith('refs/heads/master')
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: cd-deploy-from-push
    template:
      name: cd-deploy-from-push-template
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'ishitasequeira/gitops2'
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: ci-dryrun-from-pr
    template:
      name: ci-dry-run-from-pr-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/gitops2') && body.ref.startsWith('refs/heads/master')
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: cd-deploy-from-push
    template:
      name: cd-deploy-from-push-template
status:
  configuration:
    generatedName: ""
